baseURL: 'https://cetragore.com'
languageCode: en-us
title: For the Gore!
build:
  writeStats: true
menus:
  main:
    - identifier: home
      url: /
      name: Home
      weight: 1
    - identifier: about
      url: /about/
      name: About
      weight: 2
    - identifier: merch
      url: "https://www.facebook.com/799535320424442/shop/all_products?sort_type=recency&on_sale=false&in_stock=false&ref_code=mini_shop_profile_plus_shop_tab_cta&ref_surface=mini_shop_product_details"
      name: Merch
      weight: 3
      params:
        target: _blank
params:
  socials:
    - url: 'https://open.spotify.com/artist/6K4B8NOZoR3oVQRsu1jfxk?si=1u-6ChHRTpK-7fUhVBCOGQ'
      name: Spotify
      icon: fab fa-spotify

    - url: 'https://www.bandcamp.com/CETRAGORE'
      name: Bandcamp
      icon: fab fa-bandcamp

    - url: 'https://instagram.com/cetragore'
      name: Instagram
      icon: fab fa-instagram

    - url: 'https://www.facebook.com/CETRAGORE'
      name: Facebook
      icon: fab fa-facebook

    - url: 'https://www.tiktok.com/@cetragore'
      name: Tiktok
      icon: fab fa-tiktok

  banner_dark: "img/cetragore_greenwhite.webp"
  banner_light: "img/cetragore_greenblack.webp"
    
